[workspace]
members = ["runner", "common", "challenges/*"]

[workspace.dependencies]
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
futures = "0.3.28"
